#!/usr/bin/env python3
"""Validate catalogs and embed translations for standalone dylib injection."""
import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]


def generate():
    catalogs = {p.stem: json.loads(p.read_text(encoding="utf8")) for p in sorted((ROOT / 'Localization').glob('*.json'))}
    english = catalogs['en']
    assert english and all(k == v for k, v in english.items()), 'English keys must equal their fallback text'
    tokens = lambda s: re.findall(r'%(?:\d+\$)?(?:lu|lld|ld|@|d|u|f|%)', s)
    for language, strings in catalogs.items():
        assert strings.keys() == english.keys(), f'{language}: missing or extra keys'
        for key, value in strings.items():
            assert isinstance(value, str) and value, f'{language}: empty {key}'
            assert tokens(key) == tokens(value), f'{language}: format arguments differ: {key}'
    for folder in ['UI', 'Native', 'Media', 'Shared', 'Jailed']:
        for path in (ROOT / folder).glob('*.m'):
            source = path.read_text(encoding="utf8")
            assert not re.search(r'@"[^"\n]*[\u3040-\u9fff]', source), f'{path}: hardcoded Japanese'
            for literal in re.findall(r'GSL\(\s*@("(?:[^"\\]|\\.)*")\s*\)', source):
                assert json.loads(literal) in english, f'{path}: unknown translation {literal}'
    quote = lambda s: '@' + json.dumps(s, ensure_ascii=False)
    lines = ['// Generated by scripts/localization.py. Edit Localization/*.json instead.', '#pragma once',
             'static inline NSDictionary *GSLocalizationCatalogs(void) {',
             ' static NSDictionary *catalogs; static dispatch_once_t once;',
             ' dispatch_once(&once, ^{ catalogs = @{']
    for language, strings in catalogs.items():
        lines.append(f'  {quote(language)}: @{{')
        lines += [f'   {quote(k)}: {quote(v)},' for k, v in sorted(strings.items())]
        lines.append('  },')
    lines += [' }; });', ' return catalogs;', '}', '']
    return '\n'.join(lines)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    content = generate()
    output = ROOT / 'Shared/GSLocalization.generated.h'
    if args.check:
        assert output.read_text(encoding="utf8") == content, 'Run python3 scripts/localization.py'
        print('PASS localization coverage, format arguments and embedded catalog')
    else:
        output.write_text(content, encoding="utf8")
